version: '3.7'

# Note: docker-compose will source .env environment variables by default.
# All environment variables are declared in this project's root .env file.
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: iitmlib-project
    container_name: iitmlib-project-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:1.17-alpine
    container_name: iitmlib-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d

  mysql:
    platform: linux/amd64
    image: mysql:5.7.34
    restart: on-failure
    hostname: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
       - 3306:3306
    environment:
      MYSQL_DATABASE: iitmlibrary
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  phpmyadmin1:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 300M

volumes:
  mysql-data:
